### ISSUE TITLE
Database Writer gets stuck in 'Reading' state causing all new messages to queue indefinitely

### ISSUE THREAD

**Issue by rbeckman-nextgen** [rbeckman-nextgen/test-mc#3399]
Periodically, the Database Writer will get stuck in the 'Reading' state.  When this happens all new messages are queued indefinitely.  The only way to start processing again is to pause/start the channel or re-deploy the channel.  When this happens the database is alive and well but Mirth gets stuck.  Here is the relevant stack trace(s) from the mirth log:

{noformat}
ERROR 2014-09-16 12:11:28,372 [pool-6-thread-1] com.mirth.connect.connectors.tcp.TcpReceiver: Error receiving message (TCP Listener "Source" on channel 6641f092-f6aa-40bd-87dd-9bf8ff9f0493).
java.net.SocketException: Socket closed
>---at java.net.SocketInputStream.socketRead0(Native Method)
>---at java.net.SocketInputStream.read(SocketInputStream.java:152)
>---at java.net.SocketInputStream.read(SocketInputStream.java:122)
>---at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
>---at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
>---at com.mirth.connect.model.transmission.framemode.FrameStreamHandler.read(FrameStreamHandler.java:120)
>---at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:560)
>---at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:462)
>---at java.util.concurrent.FutureTask.run(FutureTask.java:262)
>---at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>---at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>---at java.lang.Thread.run(Thread.java:744)
ERROR 2014-09-16 12:11:28,949 [Thread-37] com.mirth.connect.donkey.server.channel.DestinationChain: Error processing destination BoxView Database Cluster.
java.lang.IllegalStateException: Pool closed
>---at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1135)
>---at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
>---at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
>---at com.mirth.connect.connectors.jdbc.DatabaseDispatcherQuery.getConnection(DatabaseDispatcherQuery.java:156)
>---at com.mirth.connect.connectors.jdbc.DatabaseDispatcherQuery.send(DatabaseDispatcherQuery.java:89)
>---at com.mirth.connect.connectors.jdbc.DatabaseDispatcherQuery.send(DatabaseDispatcherQuery.java:127)
>---at com.mirth.connect.connectors.jdbc.DatabaseDispatcherQuery.send(DatabaseDispatcherQuery.java:81)
>---at com.mirth.connect.connectors.jdbc.DatabaseDispatcher.send(DatabaseDispatcher.java:107)
>---at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:599)
>---at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:336)
>---at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:224)
>---at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1428)
>---at com.mirth.connect.donkey.server.channel.Channel.processSourceQueue(Channel.java:1530)
>---at com.mirth.connect.donkey.server.channel.Channel.run(Channel.java:1517)
>---at java.lang.Thread.run(Thread.java:744)
{noformat}

Imported Issue. Original Details:
Reporter: marksigep
Created: 2014-09-16T22:40:49.000-0700

**Comment by rbeckman-nextgen** [comment]
Patches for trunk and 3.0.3 to catch exception.  Exception can be safely ignored since the data source will be closed and re-opened in the follow code.

Imported Comment. Original Details:
Author: marksigep
Created: 2014-09-17T04:52:20.000-0700

**Comment by rbeckman-nextgen** [comment]
Investigate whether this still happens in 3.2.

Imported Comment. Original Details:
Author: narupley
Created: 2015-04-28T08:21:27.000-0700

**Comment by rbeckman-nextgen** [comment]
I do not believe this is an issue anymore after the switch to HikariCP.

Imported Comment. Original Details:
Author: marksigep
Created: 2015-09-02T19:58:20.000-0700

**Comment by rbeckman-nextgen** [comment]
This should no longer be an issue since the call to dataSource.getConnection is inside a try..catch now.

Imported Comment. Original Details:
Author: narupley
Created: 2017-01-29T10:40:19.000-0800
