### ISSUE TITLE
Unable to open a channel that has SSLProperties in Mirth Connect without SSL Plugin

### ISSUE THREAD

**Issue by rbeckman-nextgen** [rbeckman-nextgen/test-mc#4277]
Client previously had the SSL manager plugin installed but has uninstalled the plugin.  

After uninstalling, he is unable to edit, enable or deploy his channels.

He is seeing the following error:  

Channel "IncomingTestresult" is invalid and cannot be edited. Original cause:
com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
---- Debugging information ----
message : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
cause-exception : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
class : java.util.HashSet
required-type : java.util.HashSet
converter-type : com.thoughtworks.xstream.converters.collections.CollectionConverter
path : /list/channelSummary[35]/channelStatus/channel/sourceConnector/properties/responseConnectorPluginProperties/com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
class[1] : com.mirth.connect.connectors.tcp.TcpReceiverProperties
converter-type[1] : com.mirth.connect.model.converters.MigratableConverter
class[2] : com.mirth.connect.model.Connector
-------------------------------
com.thoughtworks.xstream.converters.ConversionException: com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
---- Debugging information ----
message : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
cause-exception : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
class : java.util.HashSet
required-type : java.util.HashSet
converter-type : com.thoughtworks.xstream.converters.collections.CollectionConverter
path : /list/channelSummary[35]/channelStatus/channel/sourceConnector/properties/responseConnectorPluginProperties/com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
class[1] : com.mirth.connect.connectors.tcp.TcpReceiverProperties
converter-type[1] : com.mirth.connect.model.converters.MigratableConverter
class[2] : com.mirth.connect.model.Connector
-------------------------------
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:101)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:101)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshall

Nick Rupley mentioned that this seems to be a problem with the TCP Listener specifically because it stores extra SSL settings for the Respond on New Connection feature.  Other connector types, like TCP Sender, work just fine after uninstalling the SSL Manager.

In the meantime you can fix by editing the channel XML and taking out the SSLConnectorProperties

Imported Issue. Original Details:
Reporter: han
Created: 2019-01-09T13:17:28.000-0800

**Comment by rbeckman-nextgen** [comment]
I had this issue last week. I got around it by doing this:
1. Export the channel to your local machine.
2. Open the XML file in a text editor (e.g., Sublime Text).
3. Look for "ssl".
4. Remove everything from the parent node. For example, <pluginProperties>sampleSslText</pluginProperties> will now be <pluginProperties></pluginProperties> or <pluginProperties/>.
5. Save the file.
5. Now import the file to Mirth.

Imported Comment. Original Details:
Author: ashishshetty1992
Created: 2019-01-22T06:34:54.000-0800

**Comment by rbeckman-nextgen** [comment]
Ah, just read the last line of your description.

Imported Comment. Original Details:
Author: ashishshetty1992
Created: 2019-01-22T06:39:14.000-0800
